{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "n8n-scraper.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n-scraper.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- if .Values.persistence.storageClass }}
  {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.persistence.selector }}
  selector:
    {{- toYaml .Values.persistence.selector | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- if and .Values.chromadb.enabled .Values.chromadb.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "n8n-scraper.fullname" . }}-chromadb-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n-scraper.labels" . | nindent 4 }}
    app.kubernetes.io/component: chromadb
  {{- with .Values.chromadb.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.chromadb.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.chromadb.persistence.size | quote }}
  {{- if .Values.chromadb.persistence.storageClass }}
  {{- if (eq "-" .Values.chromadb.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.chromadb.persistence.storageClass | quote }}
  {{- end }}
  {{- end }}
---
{{- end }}
{{- if and .Values.redis.enabled .Values.redis.master.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "n8n-scraper.fullname" . }}-redis-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n-scraper.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  {{- with .Values.redis.master.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.redis.master.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.redis.master.persistence.size | quote }}
  {{- if .Values.redis.master.persistence.storageClass }}
  {{- if (eq "-" .Values.redis.master.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.redis.master.persistence.storageClass | quote }}
  {{- end }}
  {{- end }}
{{- end }}