{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "n8n-scraper.serviceAccountName" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n-scraper.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "n8n-scraper.serviceAccountName" . }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n-scraper.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "n8n-scraper.serviceAccountName" . }}-monitoring
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n-scraper.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
{{- end }}
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "n8n-scraper.fullname" . }}-api
  labels:
    {{- include "n8n-scraper.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "n8n-scraper.fullname" . }}-worker
  labels:
    {{- include "n8n-scraper.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "n8n-scraper.fullname" . }}-monitoring
  labels:
    {{- include "n8n-scraper.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "n8n-scraper.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n-scraper.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
subjects:
- kind: ServiceAccount
  name: {{ include "n8n-scraper.serviceAccountName" . }}-api
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "n8n-scraper.fullname" . }}-api
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "n8n-scraper.fullname" . }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n-scraper.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
subjects:
- kind: ServiceAccount
  name: {{ include "n8n-scraper.serviceAccountName" . }}-worker
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "n8n-scraper.fullname" . }}-worker
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "n8n-scraper.fullname" . }}-monitoring
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n-scraper.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
subjects:
- kind: ServiceAccount
  name: {{ include "n8n-scraper.serviceAccountName" . }}-monitoring
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "n8n-scraper.fullname" . }}-monitoring
  apiGroup: rbac.authorization.k8s.io
---
{{- if .Values.rbac.clusterRole.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "n8n-scraper.fullname" . }}-cluster-reader
  labels:
    {{- include "n8n-scraper.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/metrics", "nodes/stats"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "n8n-scraper.fullname" . }}-cluster-reader
  labels:
    {{- include "n8n-scraper.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "n8n-scraper.serviceAccountName" . }}-monitoring
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "n8n-scraper.fullname" . }}-cluster-reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}