# Database Configuration
vector_db:
  provider: "chromadb"
  path: "/Users/user/Projects/n8n-projects/n8n-web-scrapper/data/databases/vector"
  collection_name: "n8n_knowledge"
  embedding_model: "text-embedding-ada-002"

knowledge_db:
  provider: "sqlite"
  path: "/Users/user/Projects/n8n-projects/n8n-web-scrapper/data/databases/sqlite/knowledge.db"
  tables:
    - documents
    - chunks
    - metadata
    - updates

cache:
  provider: "redis"
  host: "localhost"
  port: 6379
  db: 0
  ttl: 3600
